routes/dashboard.php
<?php

Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
Route::get('/contract', ['as' => 'dashboard', 'uses' => 'ContractController@create']);
Route::get('/contract/{id}', ['as' => 'edit', 'uses' => 'ContractController@edit']);
Route::post('/contract/store', ['as' => 'store', 'uses' => 'ContractController@store']);
Route::get('/contract/zip/{id}', ['as' => 'zip', 'uses' => 'ContractController@zip']);
Route::put('/contract/update/{id}', ['as' => 'customer.update', 'uses' => 'ContractController@update']);
Route::delete('/contract/delete/{id}', ['as' => 'customers.destroy', 'uses' => 'ContractController@destroy']);
Route::get('/users/pdf', ['as' => 'pdf', 'uses' => 'UserController@pdf']);
Route::resource('users','UserController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);
Route::match(['get', 'post'], 'register', function(){
    return redirect('/login');
}); 

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','surname','phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Dashboard/ContractController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Customer;
use App\Http\Controllers\Controller;
use Chumper\Zipper\Zipper;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Support\Facades\Storage;

class ContractController extends Controller
{
    public function create()
    {
        return view('dashboard.contracts.create');

    }
    public function edit($id)
    {
        $customer = Customer::find($id);
        return view('dashboard.contracts.edit',compact('customer'));

    }

    public function store(Request $request)
    {

        $date = $request->date;
        $passport =$request->passport_date;
        $customer = Customer::create($request->all());
        $pdf = PDF::loadView('pdf.mrgi-paymanagir', array('customer' => $customer,'date'=>$date,'passport'=>$passport));
        $pdf2 = PDF::loadView('pdf.gnman-akt', array('customer' => $customer,'date'=>$date,'passport'=>$passport));
        $pdf3 = PDF::loadView('pdf.eo', array('customer' => $customer,'date'=>$date,'passport'=>$passport));
        Storage::disk('public')->put('pdf/mrgi_paymanagir' . $customer->id . '.pdf', $pdf->output());
        Storage::disk('public')->put('pdf/gnman_akt' . $customer->id . '.pdf', $pdf2->output());
        Storage::disk('public')->put('pdf/eo' . $customer->id . '.pdf', $pdf3->output());
        $customer['mrgi_paymanagir'] = 'pdf/mrgi_paymanagir' . $customer->id . '.pdf';
        $customer['gnman_akt'] = 'pdf/gnman_akt' . $customer->id . '.pdf';
        $customer['eo'] = 'pdf/eo' . $customer->id . '.pdf';
        $customer['date'] = $date;
        $customer['passport_date'] = $passport;
        $customer->save();
//        $zipper = new Zipper();
//        $zipper->make('public/storage/zips/zip'.$customer->id .'.zip')->add(['storage/pdf/eo'.$customer->id .'.pdf','storage/pdf/gnman_akt'.$customer->id .'.pdf','storage/pdf/mrgi_paymanagir'.$customer->id .'.pdf']);

        return redirect()->route('users.index');

    }
 public function update(Request $request,$id)
    {
            $customer = Customer::find($id);
        if (!$customer) {
            abort(404);
        }
        $date = $request->date;
        $passport = $request->passport_date;
        $customer->update($request->all());

        $pdf = PDF::loadView('pdf.mrgi-paymanagir', array('customer' => $customer,'date'=>$date,'passport'=>$passport));
        $pdf2 = PDF::loadView('pdf.gnman-akt', array('customer' => $customer,'date'=>$date,'passport'=>$passport));
        $pdf3 = PDF::loadView('pdf.eo', array('customer' => $customer,'date'=>$date,'passport'=>$passport));
        Storage::disk('public')->put('pdf/mrgi_paymanagir' . $customer->id . '.pdf', $pdf->output());
        Storage::disk('public')->put('pdf/gnman_akt' . $customer->id . '.pdf', $pdf2->output());
        Storage::disk('public')->put('pdf/eo' . $customer->id . '.pdf', $pdf3->output());
        $customer['mrgi_paymanagir'] = 'pdf/mrgi_paymanagir' . $customer->id . '.pdf';
        $customer['gnman_akt'] = 'pdf/gnman_akt' . $customer->id . '.pdf';
        $customer['eo'] = 'pdf/eo' . $customer->id . '.pdf';
        $customer['date'] = $date;
        $customer['passport_date'] = $passport;
        $customer->save();
//        $zipper = new Zipper();
//        $zipper->make('public/storage/zips/zip'.$id.'.zip')->add(['storage/pdf/eo'.$id.'.pdf','storage/pdf/gnman_akt'.$id.'.pdf','storage/pdf/mrgi_paymanagir'.$id.'.pdf']);

        return redirect()->route('users.index');

    }

    public function destroy($id)
    {
        $customer = Customer::find($id);

        $customer->delete();
        return redirect()->route('users.index');
    }
    public  function zip($id)
    {
          return response()->download('public/storage/zips/zip'.$id.'.zip');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('dashboard.dashboard');
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Auto;
use App\AutoModel;
use App\Customer;
use App\Http\Controllers\Controller;
use App\Http\Requests\PartRequest;
use App\Part;
use App\User;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {


     $users = User::all();
     $customers= Customer::paginate(10);

        return view('dashboard.users.index', compact('users','customers'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        $pdf = PDF::loadView('pdf.vors');
        return $pdf->download('invoice.pdf');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $part = Part::find($id);

        if (!$part) {
            abort(404);
        }


        return view('dashboard.parts.edit', compact('part'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(PartRequest $request, $id)
    {
        $part = Part::find($id);
        if (!$part) {
            abort(404);
        }
        $part->update($request->all());

        return redirect()->route('parts.index', ['car_id' => AutoModel::where('id', $part->model_id)->first()->auto_id, 'model_id' => $part->model_id, 'modification_id' => $part->modification_id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        $user->delete();
        return redirect()->route('users.index');
    }

}

resources/views/dashboard/users/edit.blade.php
@extends('dashboard.layouts.app')
@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
@endsection

@section('content')

    <div class="container-fluid white-bg pb-5 mt-5">
        <div class="row">

            <div class="col-md-12">

                @if(\Illuminate\Support\Facades\Request::route()->uri == 'dashboard/adminsEdit/{id}/edit')

                    <a href="{{ route('admins') }}" title="Վերադառնալ"
                       class="add btn btn-outline btn-success mt-2"><i class="fa fa-arrow-left" aria-hidden="true"></i>
                        Վերադառնալ

                    </a>
                @else
                    <a href="{{ route('users.index') }}" title="Վերադառնալ"
                       class="add btn btn-outline btn-success mt-2"><i class="fa fa-arrow-left" aria-hidden="true"></i>
                        Վերադառնալ

                    </a>


                @endif

                <h2 class="text-center pt-2 pb-3"> </h2>
                <form action="{{route('users.update',$user->id)}}" method="post" class="form-horizontal"
                      enctype="multipart/form-data">
                    {!! csrf_field() !!}
                    <input type="hidden" name="_method" value="PUT">
                    <div class="row">

                        <div class="col-md-12 col-sm-12">
                            @if(\Illuminate\Support\Facades\Request::route()->uri !== 'dashboard/adminsEdit/{id}/edit')
                            <div class="form-group row">
                                <div class="col-sm-3 control-label font-weight-bold">Անձի Տեսակ:</div>
                                <div class="col-sm-6">
                                    <select class="form-control" name="type" id="type">
                                        <option value="iravaban" @if($user->type == "iravaban") selected @endif>
                                            Իրավաբանական
                                        </option>
                                        <option value="anhat" @if($user->type == "anhat") selected @endif>Անհատ Ձեռնարկատեր</option>
                                        <option value="fizikakan" @if($user->type == "fizikakan") selected @endif>
                                            Ֆիզիկական
                                        </option>
                                    </select>
                                    {!! $errors->first('type', '<p style="color:red" class="help-block">:message</p>') !!}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-3 control-label font-weight-bold">Անձնագիր:</div>

                                <div class="col-sm-6">
                                @if($user->files)

                                    @foreach($user->files as $file)
                                        <a href="/storage/{{$file->passport}}" download class="mb-1 d-block">Անձնագիր   {{ $loop->iteration }}</a>
                                    @endforeach
                                @endif
                                <input id="passport" type="file" class="form-control" name="passport[]"  placeholder="{{trans('register.passport')}}" multiple>

                            </div>
                            </div>
                                <div class="form-group row">
                                    <div class="col-sm-3 control-label font-weight-bold">Հեռախոսահամար:</div>
                                    <div class="col-sm-6">
                                        <input type='text' id="phone" name="phone" class='form-control' placeholder='12 123-456'
                                               value="{{$user->details->phone}}">
                                        {!! $errors->first('phone', '<p style="color:red" class="help-block">:message</p>') !!}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-3 control-label font-weight-bold">Հասցե:</div>
                                    <div class="col-sm-6">
                                        <input type='text' name="address" class='form-control' placeholder='Հասցե'
                                               value="{{$user->details->address}}">
                                        {!! $errors->first('address', '<p style="color:red" class="help-block">:message</p>') !!}
                                    </div>
                                </div>
                            @endif
                            <div class="form-group row">
                                <div class="col-sm-3 control-label font-weight-bold">Անուն:</div>
                                <div class="col-sm-6">
                                    <input type='text' name="first_name" class='form-control'
                                           placeholder='Անուն Ազգանուն' value="{{$user->first_name}}">
                                    {!! $errors->first('first_name', '<p style="color:red" class="help-block">:message</p>') !!}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-3 control-label font-weight-bold">Էլեկտրոնային Հասցե:</div>
                                <div class="col-sm-6">
                                    <input type='text' name="email" class='form-control'
                                           placeholder='Էլեկտրոնային Հասցե' value="{{$user->email}}">
                                    {!! $errors->first('email', '<p style="color:red" class="help-block">:message</p>') !!}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-3 control-label font-weight-bold">Գաղտնաբառ:</div>
                                <div class="col-sm-6">
                                    <input type='password' name="password" class='form-control'
                                           autocomplete="new-password" placeholder='Գաղտնաբառ'>
                                    {!! $errors->first('password', '<p style="color:red" class="help-block">:message</p>') !!}
                                </div>
                            </div>

                            @if(\Illuminate\Support\Facades\Request::route()->uri == 'dashboard/adminsEdit/{id}/edit')

                            <div class="form-group row">
                                <div class="col-sm-3 control-label font-weight-bold">Դեր:</div>
                                <div class="col-sm-6">
                                    {!! Form::select('role_id', $roles, isset($user->roles[0]->id) ? $user->roles[0]->id : null, ['class' => 'form-control']) !!}

                                    {!! $errors->first('role_id', '<p style="color:red" class="help-block">:message</p>') !!}
                                </div>
                            </div>
                            @else
                                <input type="hidden" name="role_id" value="6">
                            @endif
                                @if(\Illuminate\Support\Facades\Request::route()->uri !== 'dashboard/adminsEdit/{id}/edit')
                            <div class="form-group row changing-line ">
                                <div class="col-sm-3 control-label font-weight-bold">Կազմակերպության Անուն:</div>
                                <div class="col-sm-6">
                                    <input type='text' name="company_name" class='form-control'
                                           placeholder='Կազմակերպության Անուն' value="{{$user->details->company_name}}">
                                    {!! $errors->first('company_name', '<p style="color:red" class="help-block">:message</p>') !!}
                                </div>
                            </div>
                            <div class="form-group row changing-line">
                                <div class="col-sm-3 control-label font-weight-bold">Պաշտոն:</div>
                                <div class="col-sm-6">
                                    <input type='text' name="position" class='form-control' placeholder='Պաշտոն'
                                           value="{{$user->details->position}}">
                                    {!! $errors->first('position', '<p style="color:red" class="help-block">:message</p>') !!}
                                </div>
                            </div>
                            <div class="form-group row changing-line">
                                <div class="col-sm-3 control-label font-weight-bold">Գրանցման Համար:</div>
                                <div class="col-sm-6">
                                    <input type='text' name="register_num" class='form-control'
                                           placeholder='Գրանցման Համար' value="{{$user->details->register_num}}">
                                    {!! $errors->first('register_num', '<p style="color:red" class="help-block">:message</p>') !!}
                                </div>
                            </div>
                                @endif
                            <div class="form-group">
                                <input type="submit" class="btn btn-success pull-right" value="Փոփոխել">
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection
@section('scripts')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.js"></script>
    <script>
        $(document).ready(function () {
            $('#phone').mask('+374 00 000-000');
            var old_type = "<?php echo $user->type; ?>";

            if (old_type == "fizikakan") {
                $(".changing-line").children().hide();
            }
        });



        $('#type').on('change', function () {
            var type = $(this).val();
            if (type == 'fizikakan') {

                $(".changing-line").children().hide();
            }
            else {
                $(".changing-line").children().show();
            }
        });
    </script>
@endsection

resources/views/dashboard/users/index.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <div class="container-fluid white-bg pb-5 mt-5">
        <div class="row">

            <div class="col-md-12">


                <h1>Ադմինիստրատորներ</h1>
                <div class="table-responsive">
                    <table class="table table-bordered mt-5">
                        <thead>
                        <tr>

                            <th>Անուն</th>
                            <th>Էլեկտրոնային Հասցե</th>
                            {{--<th>Գործողություններ</th>--}}

                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td scope="row">{{$user->name}}</td>
                                <td scope="row">{{$user->email}}</td>


                                {{--<td>--}}
                                    {{--<div class="btn-group my-btn-group">--}}



                                            {{--<a href="{{ route('users.edit', $user->id) }}">--}}
                                                {{--<i class="fa fa-pencil-square-o"></i>--}}
                                            {{--</a>--}}


                                        {{--<form method="POST" action="{{ route('users.destroy',  $user->id) }}"--}}
                                              {{--accept-charset="UTF-8">--}}
                                            {{--{{ method_field('DELETE') }}--}}
                                            {{--{{ csrf_field() }}--}}
                                            {{--<button type="submit">--}}
                                                {{--<i id="delete-id" data-toggle="confirmation" class="fa fa-trash-o"--}}
                                                   {{--aria-hidden="true">--}}
                                                {{--</i>--}}
                                            {{--</button>--}}

                                        {{--</form>--}}


                                    {{--</div>--}}
                                {{--</td>--}}
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <h1>Վաճառողներ</h1>
                <div class="table-responsive">
                    <table class="table table-bordered mt-5">
                        <thead>
                        <tr>

                            <th>ID</th>
                            <th>Անուն</th>
                            <th>Ազգանուն</th>
                            <th>Անձնագրի Սերիա</th>
                            <th>Պայմանագրի Տարեթիվ</th>
                            <th>Հեռախոս</th>
                            <th>Մրգի Պայմանագիր</th>
                            <th>Գնման Ակտ</th>
                            <th>Ելքի Օրդեր</th>
                            <th>Գործողություններ</th>

                        </tr>
                        </thead>
                        <tbody>
                        @foreach($customers as $customer)
                            <tr>
                                <td scope="row">{{$customer->id}}</td>
                                <td scope="row">{{$customer->name}}</td>
                                <td scope="row">{{$customer->surname}}</td>
                                <td scope="row">{{$customer->passport_seria}}</td>
                                <td scope="row">{{$customer->date}}</td>
                                <td scope="row">{{$customer->phone}}</td>
                                <td scope="row"><a href="/storage/{{$customer->mrgi_paymanagir}}">Ներբեռնել Մրգի Պայմանագիր</a></td>
                                <td scope="row"> <a href="/storage/{{$customer->gnman_akt}}">Ներբեռնել Գնման Ակտ</a></td>
                                <td scope="row"> <a href="/storage/{{$customer->eo}}">Ներբեռնել Ելքի Օրդերը</a></td>



                                <td>
                                    <div class="btn-group my-btn-group">


                                        <a href="{{URL::to('dashboard/contract/' .$customer->id)}}">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>

                                        </a>
                                        {{--<a href="/dashboard/contract/zip/{{$customer->id}}">--}}
                                          {{--Ներբեռնել Բոլորը Zip--}}

                                        {{--</a>--}}

                                        <form method="POST" action="{{ route('customers.destroy',  $customer->id) }}"
                                              accept-charset="UTF-8">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit">
                                                <i id="delete-id" data-toggle="confirmation" class="fa fa-trash-o"
                                                   aria-hidden="true">
                                                </i>
                                            </button>

                                        </form>


                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="pull-right pt-2">
                    {{$customers->links()}}
                </div>
            </div>

        </div>


    </div>
@endsection
@section('scripts')

    <script src="/js/bootstrap-confirmation.js"></script>
    <script>
        $('[data-toggle=confirmation]').confirmation({
            rootSelector: '[data-toggle=confirmation]',
        });
    </script>

@endsection